wedding_planner/config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :calendars
  resources :add_google_oauth_to_u_sers_for_calendars
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :calendars, only: [:calendars, :events, :new_event]

  # calendar routes
  get "/redirect", to: "calendars#redirect"
  get "/callback", to: "calendars#callback"
  get "/calendars", to: "calendars#calendars"
  get '/events/:calendar_id', to: 'calendars#events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendars#new_event', calendar_id: /[^\/]+/


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

wedding_planner/app/models/add_google_oauth_to_u_sers_for_calendar.rb
class AddGoogleOauthToUSersForCalendar < ApplicationRecord
end

wedding_planner/app/controllers/add_google_oauth_to_u_sers_for_calendars_controller.rb
class AddGoogleOauthToUSersForCalendarsController < ApplicationController
  before_action :set_add_google_oauth_to_u_sers_for_calendar, only: %i[ show edit update destroy ]

  # GET /add_google_oauth_to_u_sers_for_calendars or /add_google_oauth_to_u_sers_for_calendars.json
  def index
    @add_google_oauth_to_u_sers_for_calendars = AddGoogleOauthToUSersForCalendar.all
  end

  # GET /add_google_oauth_to_u_sers_for_calendars/1 or /add_google_oauth_to_u_sers_for_calendars/1.json
  def show
  end

  # GET /add_google_oauth_to_u_sers_for_calendars/new
  def new
    @add_google_oauth_to_u_sers_for_calendar = AddGoogleOauthToUSersForCalendar.new
  end

  # GET /add_google_oauth_to_u_sers_for_calendars/1/edit
  def edit
  end

  # POST /add_google_oauth_to_u_sers_for_calendars or /add_google_oauth_to_u_sers_for_calendars.json
  def create
    @add_google_oauth_to_u_sers_for_calendar = AddGoogleOauthToUSersForCalendar.new(add_google_oauth_to_u_sers_for_calendar_params)

    respond_to do |format|
      if @add_google_oauth_to_u_sers_for_calendar.save
        format.html { redirect_to @add_google_oauth_to_u_sers_for_calendar, notice: "Add google oauth to u sers for calendar was successfully created." }
        format.json { render :show, status: :created, location: @add_google_oauth_to_u_sers_for_calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @add_google_oauth_to_u_sers_for_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_google_oauth_to_u_sers_for_calendars/1 or /add_google_oauth_to_u_sers_for_calendars/1.json
  def update
    respond_to do |format|
      if @add_google_oauth_to_u_sers_for_calendar.update(add_google_oauth_to_u_sers_for_calendar_params)
        format.html { redirect_to @add_google_oauth_to_u_sers_for_calendar, notice: "Add google oauth to u sers for calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @add_google_oauth_to_u_sers_for_calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @add_google_oauth_to_u_sers_for_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_google_oauth_to_u_sers_for_calendars/1 or /add_google_oauth_to_u_sers_for_calendars/1.json
  def destroy
    @add_google_oauth_to_u_sers_for_calendar.destroy!

    respond_to do |format|
      format.html { redirect_to add_google_oauth_to_u_sers_for_calendars_path, status: :see_other, notice: "Add google oauth to u sers for calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_google_oauth_to_u_sers_for_calendar
      @add_google_oauth_to_u_sers_for_calendar = AddGoogleOauthToUSersForCalendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_google_oauth_to_u_sers_for_calendar_params
      params.fetch(:add_google_oauth_to_u_sers_for_calendar, {})
    end
end

wedding_planner/app/helpers/add_google_oauth_to_u_sers_for_calendars_helper.rb
module AddGoogleOauthToUSersForCalendarsHelper
end

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/_add_google_oauth_to_u_sers_for_calendar.html.erb
<div id="<%= dom_id add_google_oauth_to_u_sers_for_calendar %>">
</div>

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/_form.html.erb
<%= form_with(model: add_google_oauth_to_u_sers_for_calendar) do |form| %>
  <% if add_google_oauth_to_u_sers_for_calendar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(add_google_oauth_to_u_sers_for_calendar.errors.count, "error") %> prohibited this add_google_oauth_to_u_sers_for_calendar from being saved:</h2>

      <ul>
        <% add_google_oauth_to_u_sers_for_calendar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/edit.html.erb
<h1>Editing add google oauth to u sers for calendar</h1>

<%= render "form", add_google_oauth_to_u_sers_for_calendar: @add_google_oauth_to_u_sers_for_calendar %>

<br>

<div>
  <%= link_to "Show this add google oauth to u sers for calendar", @add_google_oauth_to_u_sers_for_calendar %> |
  <%= link_to "Back to add google oauth to u sers for calendars", add_google_oauth_to_u_sers_for_calendars_path %>
</div>

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Add google oauth to u sers for calendars</h1>

<div id="add_google_oauth_to_u_sers_for_calendars">
  <% @add_google_oauth_to_u_sers_for_calendars.each do |add_google_oauth_to_u_sers_for_calendar| %>
    <%= render add_google_oauth_to_u_sers_for_calendar %>
    <p>
      <%= link_to "Show this add google oauth to u sers for calendar", add_google_oauth_to_u_sers_for_calendar %>
    </p>
  <% end %>
</div>

<%= link_to "New add google oauth to u sers for calendar", new_add_google_oauth_to_u_sers_for_calendar_path %>

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/new.html.erb
<h1>New add google oauth to u sers for calendar</h1>

<%= render "form", add_google_oauth_to_u_sers_for_calendar: @add_google_oauth_to_u_sers_for_calendar %>

<br>

<div>
  <%= link_to "Back to add google oauth to u sers for calendars", add_google_oauth_to_u_sers_for_calendars_path %>
</div>

wedding_planner/app/views/add_google_oauth_to_u_sers_for_calendars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @add_google_oauth_to_u_sers_for_calendar %>

<div>
  <%= link_to "Edit this add google oauth to u sers for calendar", edit_add_google_oauth_to_u_sers_for_calendar_path(@add_google_oauth_to_u_sers_for_calendar) %> |
  <%= link_to "Back to add google oauth to u sers for calendars", add_google_oauth_to_u_sers_for_calendars_path %>

  <%= button_to "Destroy this add google oauth to u sers for calendar", @add_google_oauth_to_u_sers_for_calendar, method: :delete %>
</div>